{% set version = "1.0" %}

package:
  name: caffe
  version: {{ version }}

source:
  url: https://github.com/BVLC/caffe/archive/{{ version }}.tar.gz
  sha256: 71d3c9eb8a183150f965a465824d01fe82826c22505f7aa314f700ace03fa77f
  patches:
    - backport_6638-support-opencv4.patch

build:
  number: 203
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - boost
    - cython
    # Unpin hdf5 when the new h5py is released.
    - hdf5 1.10.4
    - gflags
    - glog
    - h5py
    - ipython
    - leveldb
    - protobuf
    - lmdb
    - mkl-include  {{ mkl }}  # [blas_impl == 'mkl']
    - mkl  {{ mkl }}  # [blas_impl == 'mkl']
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    # Some of its dependencies are not built with openblas 0.3.6 yet.
    - openblas  # [blas_impl == 'openblas']
    - matplotlib
    - networkx
    - nose
    - opencv
    - pandas
    - pillow
    - python-dateutil
    - python-gflags
    - python-leveldb
    - pyyaml
    - scikit-image
    - six
    - snappy
    - numpy
  run:
    - python
    - boost
    - h5py
    - ipython
    - matplotlib
    - networkx
    - {{ pin_compatible('numpy') }}
    - pandas
    - protobuf
    - python-dateutil
    - python-gflags
    - python-leveldb
    - pyyaml
    - scikit-image
    - scipy
    - six

test:
  commands:
    # Test commands.
    - command -v "${PREFIX}/bin/caffe"
    - command -v "${PREFIX}/bin/classification"
    - command -v "${PREFIX}/bin/classify"
    - command -v "${PREFIX}/bin/compute_image_mean"
    - command -v "${PREFIX}/bin/convert_cifar_data"
    - command -v "${PREFIX}/bin/convert_imageset"
    - command -v "${PREFIX}/bin/convert_mnist_data"
    - command -v "${PREFIX}/bin/convert_mnist_siamese_data"
    - command -v "${PREFIX}/bin/detect"
    - command -v "${PREFIX}/bin/device_query"
    - command -v "${PREFIX}/bin/draw_net"
    - command -v "${PREFIX}/bin/extract_features"
    - command -v "${PREFIX}/bin/finetune_net"
    - command -v "${PREFIX}/bin/net_speed_benchmark"
    - command -v "${PREFIX}/bin/test_net"
    - command -v "${PREFIX}/bin/train_net"
    - command -v "${PREFIX}/bin/upgrade_net_proto_binary"
    - command -v "${PREFIX}/bin/upgrade_net_proto_text"
    - command -v "${PREFIX}/bin/upgrade_solver_proto_text"

    # Test includes.
    - test -d "${PREFIX}/include/caffe"

    # Test libraries.
    - test -f "${PREFIX}/lib/libcaffe.so"

  imports:
    - caffe

about:
  home: http://caffe.berkeleyvision.org/
  license: BSD-2-Clause
  summary: "A deep learning framework made with expression, speed, and modularity in mind"
  description: |
    Caffe is a deep learning framework brewed for expression, speed,modularity, openness and community.
  doc_url: http://caffe.berkeleyvision.org/tutorial/
  doc_source_url: https://github.com/BVLC/caffe

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - marcelotrevisani
    - ocefpaf
