travis:
  secure:
    BINSTAR_TOKEN: Bs105wVDt+Bq3TqPW3pugrnwki7e0ketyo4XDlZWp6kwVIaWS28HEcN0ttWTptZBqnJab8xyoPHXA+uPYRKKrFYYTp/sMMcifdp7jAnArSYh87jihYWMtN5d49gZXGXTOSXTwiDNFiPWv4RPL3fOneLviZg4VHGIozjWXw48s107QPH4L2TWg6LppOL9xUevpI+IKHCfPI//lvIiHiGA2O7hfEPmEzEM76wHlzjRtORSDHh7B7Y8S4hXNTM2eMpcvBUtuEIsw8XHbDdL1TXuz7Efp7GejlzoplUPxVmCmGfPSUs97dsv6OF/F14mTJU5bizuGWn3aKCv3dfDcHtKrVtLLaNjvaphXNVV5aY07biOOT2CmMj2kl+FT2Y329zxIFeXVjK1p64+8SSRZYAI+EP6RNKU2qmASp23kr2k0LNdFZASXzUrO+oJV49v/pZtZ03KQAOwfu9CJ8RDQXDvFEnboIlaSzv+KN3f8sOj7M1zGe4+FDVBPd19C6eMm+Y3Ly6qJQZ70LYTasCeMCNoqfvOLpmPd/BaV/LkeLiAEZSb07HnIRcWbejH+DjPK1XTqsNWlcrHevy8hjKtASbnk7rJlbuD4R0zXH4uO+wkrwHUUAh19ct355lcCAHHdmCObk9K1yLI8XkUUuNOrCI7J2TLHrJ6hwTisAxjVukjUDc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
